// Copyright 2023 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
#define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

include "iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td"

#endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS


#ifndef PYTHON_BINDINGS_IREE_GPU_EXTENSIONS_OPS
#define PYTHON_BINDINGS_IREE_GPU_EXTENSIONS_OPS

include "iree/compiler/Codegen/Dialect/GPU/TransformExtensions/IREEGPUExtensionsOps.td"

#endif // PYTHON_BINDINGS_IREE_GPU_EXTENSIONS_OPS


#ifndef PYTHON_BINDINGS_IREE_LLVMGPU_EXTENSIONS_OPS
#define PYTHON_BINDINGS_IREE_LLVMGPU_EXTENSIONS_OPS

include "iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td"

#endif // PYTHON_BINDINGS_IREE_LLVMGPU_EXTENSIONS_OPS


// #ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
// #define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

// include "iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td"

// #endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS



// #ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
// #define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

// include "iree/compiler/Dialect/LinalgExt/TransformExtensions/LinalgExtExtensionsOps.td"

// #endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS



// #ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
// #define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

// include "iree/compiler/Dialect/Util/TransformOps/UtilTransformOps.td"

// #endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS



// #ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
// #define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

// include "iree/compiler/Preprocessing/TransformExtensions/PreprocessingExtensionsOps.td"

// #endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS



// #ifndef PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
// #define PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS

// include "llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.td"

// #endif // PYTHON_BINDINGS_IREE_COMMON_EXTENSIONS_OPS
